name: Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :desktop:packageMsi --stacktrace

      - name: Publish windows version
        if: ${{ github.event_name == 'push' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "windows-latest"
          prerelease: true
          title: "Development Build"
          files: |
            README.md
            desktop/build/compose/binaries/main/msi/*.msi

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :desktop:packageDeb --stacktrace

      - name: Publish ubuntu version
        if: ${{ github.event_name == 'push' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "ubuntu-latest"
          prerelease: true
          title: "Development Build"
          files: |
            README.md
            desktop/build/compose/binaries/main/deb/*.deb

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :desktop:packageDmg --stacktrace
      - name: Publish macOS version
        if: ${{ github.event_name == 'push' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "macos-latest"
          prerelease: true
          title: "Development Build"
          files: |
            README.md
            desktop/build/compose/binaries/main/dmg/*.dmg


  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :android:assembleRelease --stacktrace
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        if: ${{ github.event_name == 'push' }}
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: android/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: Publish android version
        if: ${{ github.event_name == 'push' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "android-latest"
          prerelease: true
          title: "Development Build"
          files: |
            android/build/outputs/apk/release/*.json
            ${{steps.sign_app.outputs.signedReleaseFile}}
            android/build/outputs/mapping/release/*.txt
